const icon = (name, size = 18) => {
  const paths = {
    grid: '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
    users: '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
    userPlus: '<path d="M15 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="8" cy="7" r="4"/><path d="M19 8v6M22 11h-6"/>',
    bell: '<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',
    calendar: '<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>',
    search: '<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',
    settings: '<path d="M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-1.8 1.8-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V20h-2.1v-.1a1.7 1.7 0 0 0-1.03-1.56 1.7 1.7 0 0 0-1.88.34l-.06.06-1.8-1.8.06-.06A1.7 1.7 0 0 0 8.6 15a1.7 1.7 0 0 0-1.56-1.03H7v-2.1h.04A1.7 1.7 0 0 0 8.6 10a1.7 1.7 0 0 0-.34-1.88L8.2 8.06l1.8-1.8.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 12.97 5.1V5h2.1v.1a1.7 1.7 0 0 0 1.03 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06 1.8 1.8-.06.06A1.7 1.7 0 0 0 19.4 10c.22.59.79 1.03 1.56 1.03H21v2.1h-.04A1.7 1.7 0 0 0 19.4 15Z"/>',
    logout: '<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9"/>',
    plus: '<path d="M12 5v14M5 12h14"/>',
    arrow: '<path d="M5 12h14M13 6l6 6-6 6"/>',
    chevron: '<path d="m6 9 6 6 6-6"/>',
    download: '<path d="M12 3v12M7 10l5 5 5-5M5 21h14"/>',
    upload: '<path d="M12 16V4M7 9l5-5 5 5M5 20h14"/>',
    more: '<circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/>',
    clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    file: '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h5"/>',
    pulse: '<path d="M3 12h4l2-7 4 14 2-7h6"/>',
    eye: '<path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/>',
    image: '<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/>',
    check: '<path d="m5 12 4 4L19 6"/>',
    alert: '<path d="M10.3 3.2 2.1 17a2 2 0 0 0 1.7 3h16.4a2 2 0 0 0 1.7-3L13.7 3.2a2 2 0 0 0-3.4 0ZM12 9v4M12 17h.01"/>',
    info: '<circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/>',
    lock: '<rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',
  };
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.info}</svg>`;
};

const patients = [
  { id: 'PT-240184', name: 'Emma Richardson', initials: 'ER', age: 34, diagnosis: 'Prolactinoma', last: '12 Aug 2026', next: '03 Sep 2026', status: 'Active', tone: 'teal' },
  { id: 'PT-240179', name: 'Noah Williams', initials: 'NW', age: 42, diagnosis: 'Non-functioning adenoma', last: '11 Aug 2026', next: '18 Sep 2026', status: 'Monitoring', tone: 'blue' },
  { id: 'PT-240161', name: 'Olivia Chen', initials: 'OC', age: 28, diagnosis: 'Cushing disease', last: '08 Aug 2026', next: '29 Aug 2026', status: 'Active', tone: 'purple' },
  { id: 'PT-240153', name: 'Liam Thompson', initials: 'LT', age: 51, diagnosis: 'Acromegaly', last: '04 Aug 2026', next: '04 Nov 2026', status: 'Active', tone: 'gold' },
  { id: 'PT-240141', name: 'Sophia Martinez', initials: 'SM', age: 39, diagnosis: 'Prolactinoma', last: '29 Jul 2026', next: '21 Aug 2026', status: 'Active', tone: 'rose' },
  { id: 'PT-240128', name: 'James Anderson', initials: 'JA', age: 47, diagnosis: 'Hypopituitarism', last: '24 Jul 2026', next: '15 Oct 2026', status: 'Monitoring', tone: 'blue' },
];

const navItems = [
  ['dashboard', 'Dashboard', 'grid'], ['patients', 'Patients', 'users'], ['create', 'New patient', 'userPlus'],
  ['schedule', 'Schedule', 'calendar'], ['notifications', 'Notifications', 'bell'],
];
const detailTabs = ['Overview', 'Timeline', 'Clinical', 'Hormones', 'MRI', 'Ophthalmology', 'Treatment', 'Follow-up', 'Documents'];

let state = { screen: 'dashboard', detailTab: 'Overview', query: '', notifications: false, timelineFilter: 'All events' };
const app = document.querySelector('#app');
const toast = document.querySelector('#toast');

function logo() { return `<span class="mark-icon">${icon('pulse', 19)}</span><span>Pituitary Care</span>`; }
function initialsFor(name) { return name.split(' ').map(n => n[0]).join('').slice(0,2); }
function button(label, type = 'primary-button', name = '') { return `<button class="${type}" ${name ? `data-action="${name}"` : ''}>${label}</button>`; }

function shell(content, active = state.screen) {
  return `<div class="app-shell">
    <aside class="sidebar">
      <div class="brand-mark">${logo()}</div>
      <div class="side-section">Workspace</div>
      ${navItems.map(([id, label, ico]) => `<button class="nav-item ${active === id ? 'active' : ''}" data-nav="${id}">${icon(ico)}<span>${label}</span>${id === 'notifications' ? '<b class="nav-badge">4</b>' : ''}</button>`).join('')}
      <div class="side-section">Manage</div>
      <button class="nav-item" data-action="settings">${icon('settings')}<span>Settings</span></button>
      <div class="sidebar-bottom"><div class="user-chip"><div class="avatar">MC</div><div><strong>Dr. Maya Chen</strong><span>Endocrinology</span></div><button class="icon-button" data-action="logout" aria-label="Log out">${icon('logout', 15)}</button></div></div>
    </aside>
    <main class="main-shell">
      <header class="topbar"><div class="topbar-left"><div class="breadcrumbs">Clinic / <strong>${active === 'patients' ? 'Patients' : active === 'create' ? 'New patient' : active === 'notifications' ? 'Notifications' : active === 'schedule' ? 'Schedule' : 'Dashboard'}</strong></div></div><div class="topbar-actions"><div class="date-chip">${icon('calendar', 14)} Wednesday, 14 Aug 2026</div><button class="icon-button" data-action="notifications" aria-label="Open notifications">${icon('bell')}<i class="notif-dot"></i></button><div class="avatar">MC</div></div></header>
      <div class="page-content">${content}</div>
    </main>
  </div>${state.notifications ? notificationPanel() : ''}`;
}

function renderLogin() {
  app.innerHTML = `<div class="login-screen"><section class="login-brand"><div class="brand-mark">${logo()}</div><div class="login-copy"><div class="eyebrow">Clinical workspace · v1.0</div><h1>See the whole<br><span style="color:#68d5d0">patient story.</span></h1><p>A calm, focused workspace for pituitary teams to track what changed, what matters now, and what comes next.</p><div class="login-signature">Built for <span>Dr. Maya Chen</span> · Endocrinology</div></div></section><section class="login-panel"><form class="login-card" id="login-form"><div class="eyebrow">Welcome back</div><h2>Sign in to your clinic</h2><p>Continue to your clinical workspace.</p><div class="form-field"><label for="email">Work email</label><input class="input" id="email" type="email" value="maya.chen@northstarclinic.com" placeholder="name@clinic.com" required></div><div class="form-field"><label for="password">Password</label><div class="password-wrap"><input class="input" id="password" type="password" value="pituitary" placeholder="Enter your password" required><button type="button" data-action="password">${icon('eye', 16)}</button></div></div><div class="login-options"><label class="check"><input type="checkbox" checked> Keep me signed in</label><button type="button" class="text-button" data-action="forgot">Forgot password?</button></div><button type="submit" class="primary-button full" data-action="login">Sign in ${icon('arrow', 15)}</button><p class="login-note">Protected workspace · Your data is encrypted and access controlled.</p></form></section></div>`;
  const loginForm = document.querySelector('#login-form');
  loginForm?.addEventListener('submit', (event) => {
    event.preventDefault();
    state.screen = 'dashboard';
    state.notifications = false;
    rerender();
    showToast('Welcome back, Dr. Chen');
  });
}

function renderDashboard() {
  const schedule = [['09:00', 'Emma Richardson', 'PT-240184', 'Follow-up', 'ER'], ['10:30', 'Oliver James', 'PT-240191', 'New patient', 'OJ'], ['11:15', 'Noah Williams', 'PT-240179', 'Follow-up', 'NW'], ['14:00', 'Sophia Martinez', 'PT-240141', 'Follow-up', 'SM']];
  return shell(`<div class="page-heading"><div><div class="eyebrow">Wednesday, 14 August 2026</div><h1>Good morning, Dr. Chen</h1><p>Here’s what needs your attention today.</p></div><div class="heading-actions">${button(`${icon('plus', 15)} Add patient`, 'primary-button', 'new-patient')}</div></div>
    <div class="metric-grid">${[['Total patients','1,284','+12 this month','users','blue-soft','blue'],['Active patients','846','65.9% of total','pulse','teal-soft','teal-dark'],['New patients','18','+4 from last month','userPlus','purple-soft','purple'],['Follow-ups due','27','8 due this week','calendar','gold-soft','gold']].map(x => `<div class="metric-card"><div class="metric-top"><span class="metric-label">${x[0]}</span><span class="metric-icon" style="background:var(--${x[4]});color:var(--${x[5]})">${icon(x[3], 16)}</span></div><div class="metric-number">${x[1]}</div><div class="metric-foot"><span class="trend-up">${x[2]}</span></div></div>`).join('')}</div>
    <div class="dashboard-grid"><section class="card"><div class="card-header"><div><h3>Today's schedule</h3><p>4 appointments · Wednesday, 14 August</p></div><button class="view-link" data-nav="schedule">View calendar ${icon('arrow', 12)}</button></div><div class="schedule-list">${schedule.map((s,i) => `<div class="schedule-row"><div class="schedule-time">${s[0]}</div><div class="schedule-person"><div class="mini-avatar">${s[4]}</div><div><strong>${s[1]}</strong><span>${s[2]}</span></div></div><span class="tag ${s[3] === 'New patient' ? 'new' : 'follow'}">${s[3]}</span></div>`).join('')}</div></section><section class="card"><div class="card-header"><div><h3>Action required</h3><p>Items that need a review</p></div><span class="tag review">4 items</span></div><div class="action-list"><div class="action-row"><i class="action-dot red"></i><div class="action-copy"><strong>Clinical alert</strong><span>Visual deterioration · Emma Richardson</span></div><b class="action-count">1</b></div><div class="action-row"><i class="action-dot gold"></i><div class="action-copy"><strong>Follow-up due</strong><span>Due within the next 7 days</span></div><b class="action-count">8</b></div><div class="action-row"><i class="action-dot blue"></i><div class="action-copy"><strong>MRI overdue</strong><span>3 patients awaiting imaging</span></div><b class="action-count">3</b></div><div class="action-row"><i class="action-dot gold"></i><div class="action-copy"><strong>Investigation overdue</strong><span>Hormone panel or visual field</span></div><b class="action-count">11</b></div></div></section></div>
    <div class="quick-panel"><div><h3>Keep the care story in view</h3><p>Open Emma Richardson’s record — last updated 2 hours ago.</p></div><button class="primary-button" data-nav="detail">Open patient record ${icon('arrow', 14)}</button></div>`); 
}

function patientRows() {
  return patients.filter(p => (p.name + p.id + p.diagnosis).toLowerCase().includes(state.query.toLowerCase())).map(p => `<tr><td><div class="patient-name"><div class="mini-avatar" style="background:var(--${p.tone === 'teal' ? 'teal-soft' : p.tone === 'purple' ? 'purple-soft' : p.tone === 'gold' ? 'gold-soft' : 'blue-soft'});color:var(--${p.tone === 'teal' ? 'teal-dark' : p.tone === 'purple' ? 'purple' : p.tone === 'gold' ? 'gold' : 'blue'})">${p.initials}</div><div><strong>${p.name}</strong><span>${p.id}</span></div></div></td><td>${p.age}</td><td>${p.diagnosis}</td><td>${p.last}</td><td>${p.next}</td><td><span class="status ${p.status.toLowerCase()}">${p.status}</span></td><td><button class="icon-button" data-nav="detail" aria-label="Open patient">${icon('arrow', 15)}</button></td></tr>`).join('');
}
function renderPatients() {
  return shell(`<div class="page-heading"><div><div class="eyebrow">Care registry</div><h1>Patients</h1><p>Search and review your patient population.</p></div><div class="heading-actions">${button(`${icon('upload', 15)} Import`, 'secondary-button', 'import')} ${button(`${icon('plus', 15)} New patient`, 'primary-button', 'new-patient')}</div></div><div class="toolbar"><div class="search-box">${icon('search', 16)}<input class="input" id="patient-search" value="${state.query}" placeholder="Search name, patient ID or diagnosis…"></div><select class="select"><option>All statuses</option><option>Active</option><option>Monitoring</option></select><select class="select"><option>Sort: Last visit</option><option>Next follow-up</option><option>Name A–Z</option></select></div><section class="card table-card"><div class="table-wrap"><table><thead><tr><th>Patient</th><th>Age</th><th>Diagnosis</th><th>Last visit</th><th>Next follow-up</th><th>Status</th><th></th></tr></thead><tbody id="patient-table">${patientRows()}</tbody></table></div><div class="table-footer"><span>Showing ${patients.length} of 1,284 patients</span><div class="pagination"><button class="page-button active">1</button><button class="page-button">2</button><button class="page-button">3</button><button class="page-button">${icon('arrow', 12)}</button></div></div></section>`);
}

function renderCreate() { return shell(`<div class="page-heading"><div><div class="eyebrow">Care registry</div><h1>Create new patient</h1><p>Add a patient record to begin longitudinal tracking.</p></div><button class="secondary-button" data-nav="patients">${icon('arrow', 14)} Back to patients</button></div><form class="card form-card" id="patient-form"><div class="form-section"><h3>Basic information</h3><div class="form-grid"><div class="form-field"><label>Patient ID</label><input class="input" value="PT-240${Math.floor(200 + Math.random()*700)}" disabled></div><div class="form-field"><label>Doctor</label><select class="select"><option>Dr. Maya Chen</option><option>Dr. Aaron Patel</option></select></div><div class="form-field"><label>Full name</label><input class="input" required placeholder="Enter patient name"></div><div class="form-field"><label>Date of birth</label><input class="input" type="date" required></div><div class="form-field"><label>Gender</label><select class="select"><option>Select gender</option><option>Female</option><option>Male</option><option>Other</option></select></div><div class="form-field"><label>Phone</label><input class="input" placeholder="+1 (000) 000-0000"></div><div class="form-field wide"><label>Address</label><input class="input" placeholder="Street address, city, state"></div></div></div><div class="form-section"><h3>Contact & first visit</h3><div class="form-grid"><div class="form-field"><label>Contact person</label><input class="input" placeholder="Name and relationship"></div><div class="form-field"><label>Contact phone</label><input class="input" placeholder="+1 (000) 000-0000"></div><div class="form-field"><label>First visit date</label><input class="input" type="date"></div><div class="form-field"><label>Referral source</label><select class="select"><option>Select source</option><option>Primary care</option><option>Emergency department</option><option>Self-referral</option></select></div><div class="form-field wide"><label>Initial notes</label><textarea class="textarea" placeholder="Add a short context for the first visit…"></textarea></div></div></div><div class="form-actions"><button type="button" class="secondary-button" data-nav="patients">Cancel</button><button type="submit" class="primary-button">Create patient ${icon('arrow', 14)}</button></div></form>`); }

function detailAside() { return `<aside class="patient-aside"><section class="card patient-profile"><div class="profile-avatar">ER</div><div><h2>Emma Richardson</h2><div class="pid">PT-240184 · 34 years</div></div><span class="diagnosis-chip">Prolactinoma</span><div class="profile-details"><div class="detail-line"><label>Current treatment</label><strong>Cabergoline · 1 mg/week</strong></div><div class="detail-line"><label>Latest MRI</label><strong>12 May 2026 · 8 × 6 mm</strong></div><div class="detail-line"><label>Latest prolactin</label><strong>24 ng/mL <span style="color:var(--teal-dark);font-size:10px">↓ within range</span></strong></div><div class="detail-line"><label>Next appointment</label><strong>03 Sep 2026 · 09:00</strong></div></div><button class="secondary-button aside-action" data-action="message">${icon('bell', 14)} Remind patient</button></section></aside>`; }
function svgChart(type='hormone') { const hormone = type === 'hormone'; return `<svg class="chart-svg" viewBox="0 0 560 180" role="img" aria-label="${hormone ? 'Prolactin trend' : 'Tumor size trend'} chart"><defs><linearGradient id="tealFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#11a7a0" stop-opacity=".18"/><stop offset="1" stop-color="#11a7a0" stop-opacity="0"/></linearGradient></defs><line class="chart-grid" x1="35" y1="18" x2="545" y2="18"/><line class="chart-grid" x1="35" y1="62" x2="545" y2="62"/><line class="chart-grid" x1="35" y1="106" x2="545" y2="106"/><line class="chart-grid" x1="35" y1="150" x2="545" y2="150"/><text class="axis-label" x="3" y="22">${hormone ? '180' : '12mm'}</text><text class="axis-label" x="7" y="110">${hormone ? '90' : '6mm'}</text><text class="axis-label" x="17" y="154">0</text>${hormone ? '<path class="chart-fill-teal" d="M35 31 L160 89 L290 125 L420 140 L545 144 L545 150 L35 150Z"/><path class="chart-line-teal" d="M35 31 L160 89 L290 125 L420 140 L545 144"/><circle class="chart-point" cx="35" cy="31" r="4"/><circle class="chart-point" cx="160" cy="89" r="4"/><circle class="chart-point" cx="290" cy="125" r="4"/><circle class="chart-point" cx="420" cy="140" r="4"/><circle class="chart-point" cx="545" cy="144" r="4"/>' : '<path class="chart-line-blue" d="M35 46 L160 64 L290 82 L420 100 L545 100"/><circle class="chart-point" style="stroke:var(--blue)" cx="35" cy="46" r="4"/><circle class="chart-point" style="stroke:var(--blue)" cx="160" cy="64" r="4"/><circle class="chart-point" style="stroke:var(--blue)" cx="290" cy="82" r="4"/><circle class="chart-point" style="stroke:var(--blue)" cx="420" cy="100" r="4"/><circle class="chart-point" style="stroke:var(--blue)" cx="545" cy="100" r="4"/>'}<text class="axis-label" x="27" y="172">Jan 25</text><text class="axis-label" x="145" y="172">Apr 25</text><text class="axis-label" x="275" y="172">Aug 25</text><text class="axis-label" x="405" y="172">Dec 25</text><text class="axis-label" x="520" y="172">Aug 26</text></svg>`; }
function renderOverview() { return `<div class="summary-grid"><div class="summary-card"><span class="summary-label">Diagnosis</span><strong>Prolactinoma</strong><span>Microadenoma</span></div><div class="summary-card"><span class="summary-label">Tumor size</span><strong>8 × 6 mm</strong><span>Stable since May 2026</span></div><div class="summary-card accent"><span class="summary-label">Latest hormone</span><strong>24 ng/mL</strong><span>Prolactin · 01 Aug 2026</span></div><div class="summary-card"><span class="summary-label">Medication</span><strong>Cabergoline</strong><span>1 mg / week</span></div><div class="summary-card alert"><span class="summary-label">Next follow-up</span><strong>03 Sep 2026</strong><span>In 20 days · 09:00</span></div></div><div class="content-grid"><div><section class="card chart-card"><div class="card-header"><div><h3>Hormone trend</h3><p>Prolactin levels · ng/mL</p></div><button class="view-link" data-tab="Hormones">View details ${icon('arrow', 12)}</button></div><div class="chart-area"><div class="chart-legend"><span class="legend"><i class="teal"></i> Prolactin</span><span class="legend" style="color:#a3afbd">Reference: 4–23</span></div>${svgChart('hormone')}</div></section><section class="card chart-card" style="margin-top:17px"><div class="card-header"><div><h3>Tumor size trend</h3><p>Maximum diameter · mm</p></div><button class="view-link" data-tab="MRI">MRI history ${icon('arrow', 12)}</button></div><div class="chart-area"><div class="chart-legend"><span class="legend"><i class="blue"></i> Maximum diameter</span></div>${svgChart('tumor')}</div></section></div><section class="card"><div class="card-header"><div><h3>Care snapshot</h3><p>Most recent clinical signals</p></div></div><div class="snapshot-list"><div class="snapshot-row"><div class="snapshot-icon">${icon('pulse',14)}</div><div><strong>Clinical status</strong><span>Stable · no red flags</span></div><span class="status active">On track</span></div><div class="snapshot-row"><div class="snapshot-icon">${icon('eye',14)}</div><div><strong>Visual field</strong><span>Normal · 12 May 2026</span></div><span class="status active">Normal</span></div><div class="snapshot-row"><div class="snapshot-icon">${icon('image',14)}</div><div><strong>MRI</strong><span>Stable · 12 May 2026</span></div><span class="status active">Stable</span></div><div class="snapshot-row"><div class="snapshot-icon">${icon('check',14)}</div><div><strong>Adherence</strong><span>Self-reported · 92%</span></div><span class="status active">Good</span></div></div><div style="padding:0 20px 20px"><button class="secondary-button full" data-tab="Timeline">View full patient timeline ${icon('arrow', 14)}</button></div></section></div>`; }
function timelineEvents() { return [{date:'01 Aug 2026', type:'Hormone result', node:'', title:'Prolactin within reference range', text:'Prolactin reduced to 24 ng/mL after dose adjustment. Patient reports improved headaches.', meta:'Dr. Maya Chen · Lab report', filter:'Labs'}, {date:'18 Jul 2026', type:'Follow-up visit', node:'', title:'Symptoms improving on current dose', text:'Headaches now occasional. No visual symptoms. Continue Cabergoline 1 mg/week.', meta:'Dr. Maya Chen · Clinical note', filter:'Visits'}, {date:'12 May 2026', type:'MRI', node:'mri', title:'MRI shows stable microadenoma', text:'Lesion measures 8 × 6 mm, unchanged from prior study. No optic chiasm compression.', meta:'Northstar Imaging · MRI report', filter:'MRI'}, {date:'24 Feb 2026', type:'Medication change', node:'med', title:'Cabergoline dose increased', text:'Increased from 0.5 mg/week to 1 mg/week due to elevated prolactin (72 ng/mL).', meta:'Dr. Maya Chen · Treatment plan', filter:'Treatment'}, {date:'08 Jan 2026', type:'First visit', node:'', title:'Initial assessment', text:'Incidental pituitary microadenoma identified following persistent headaches and irregular cycles.', meta:'Dr. Maya Chen · Clinical note', filter:'Visits'}]; }
function renderTimeline() { const filtered = timelineEvents().filter(e => state.timelineFilter === 'All events' || e.filter === state.timelineFilter); return `<div class="timeline-toolbar"><div class="filter-group">${['All events','Visits','Labs','MRI','Treatment'].map(x => `<button class="filter-pill ${state.timelineFilter === x ? 'active' : ''}" data-filter="${x}">${x}</button>`).join('')}</div><button class="secondary-button" data-action="export">${icon('download', 14)} Export timeline</button></div><section class="card"><div class="card-header"><div><h3>Patient timeline</h3><p>Every clinical event, in one chronological view</p></div><button class="primary-button" data-action="add-event">${icon('plus', 14)} Add event</button></div><div class="timeline">${filtered.map(e => `<div class="timeline-event"><div class="timeline-date">${e.date}<br><span>${e.type}</span></div><div class="timeline-node ${e.node}"></div><article class="timeline-card"><div class="timeline-card-top"><h4>${e.title}</h4><button class="expand-icon">${icon('more', 16)}</button></div><p>${e.text}</p><div class="meta">${icon('file', 11)} ${e.meta}</div></article></div>`).join('')}</div></section>`; }
function renderClinical() { return `<div class="clinical-grid"><section class="card"><div class="card-header"><div><h3>Symptoms</h3><p>Reported at the latest visit</p></div><button class="view-link" data-action="save">Edit</button></div><div class="check-list">${['Headache','Visual symptoms','Menstrual disturbance','Fatigue','Polyuria','Other symptoms'].map((x,i) => `<label class="check-row"><span>${x}</span><input type="checkbox" ${[0,3].includes(i) ? 'checked' : ''}></label>`).join('')}</div></section><section><div class="card"><div class="card-header"><div><h3>Red flags</h3><p>Escalate when selected</p></div>${icon('alert', 17)}</div><div class="check-list">${['Severe headache','Visual deterioration','Ophthalmoplegia'].map(x => `<label class="check-row"><span>${x}</span><input type="checkbox"></label>`).join('')}</div></div><div class="red-flag">${icon('alert',18)}<div><strong>Urgent Alert</strong><span>Selecting a red flag will notify the clinical team and pin an alert to the patient timeline.</span></div></div></section></div><section class="card" style="margin-top:17px"><div class="card-header"><div><h3>Clinical note</h3><p>18 July 2026 · Dr. Maya Chen</p></div><button class="secondary-button" data-action="save">${icon('file', 14)} Save note</button></div><div style="padding:0 20px 20px"><textarea class="textarea">Patient reports improved headache frequency since the last dose adjustment. No visual field complaints. Continue current plan and repeat prolactin before next visit.</textarea></div></section>`; }
function renderHormones() { return `<section class="card module-card"><div class="card-header"><div><h3>Hormone results</h3><p>Longitudinal laboratory monitoring</p></div><button class="primary-button" data-action="add-result">${icon('plus',14)} Add result</button></div><div class="chart-area" style="padding-top:5px"><div class="chart-legend"><span class="legend"><i class="teal"></i> Prolactin</span><span class="legend" style="color:#a3afbd">Reference range: 4–23 ng/mL</span></div>${svgChart('hormone')}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Test</th><th>Result</th><th>Unit</th><th>Reference range</th><th>Laboratory</th></tr></thead><tbody><tr><td>01 Aug 2026</td><td><strong style="color:var(--navy)">Prolactin</strong></td><td><strong style="color:var(--teal-dark)">24</strong></td><td>ng/mL</td><td>4 – 23</td><td>Northstar Labs</td></tr><tr><td>03 Apr 2026</td><td><strong style="color:var(--navy)">Prolactin</strong></td><td><strong>72</strong></td><td>ng/mL</td><td>4 – 23</td><td>Northstar Labs</td></tr><tr><td>01 Jan 2026</td><td><strong style="color:var(--navy)">Prolactin</strong></td><td><strong style="color:var(--red)">180</strong></td><td>ng/mL</td><td>4 – 23</td><td>City Medical Lab</td></tr></tbody></table></div></section>`; }
function renderMRI() { return `<div class="content-grid"><section class="card module-card"><div class="card-header"><div><h3>MRI history</h3><p>Imaging records and reports</p></div><button class="primary-button" data-action="add-mri">${icon('upload',14)} Add MRI</button></div><div class="document-list"><div class="document-row"><div class="file-icon">MRI</div><div><strong>Brain MRI · 12 May 2026</strong><span>Stable microadenoma · 8 × 6 mm · Northstar Imaging</span></div><span class="status active">Reviewed</span><button class="icon-button">${icon('download',14)}</button></div><div class="document-row"><div class="file-icon">MRI</div><div><strong>Brain MRI · 10 Jan 2025</strong><span>Microadenoma · 9 × 6 mm · Northstar Imaging</span></div><span class="status active">Reviewed</span><button class="icon-button">${icon('download',14)}</button></div></div></section><section class="card chart-card"><div class="card-header"><div><h3>Tumor size trend</h3><p>Maximum diameter</p></div></div><div class="chart-area">${svgChart('tumor')}</div></section></div><section class="card" style="margin-top:17px"><div class="card-header"><div><h3>Latest MRI report</h3><p>12 May 2026 · Reviewed by Dr. Maya Chen</p></div><button class="secondary-button" data-action="open-file">${icon('file',14)} Open report</button></div><p class="module-note">Stable 8 × 6 mm left pituitary microadenoma. No suprasellar extension or optic chiasm compression. No new focal abnormality.</p></section>`; }
function renderTreatment() { return `<div class="content-grid"><section class="card module-card"><div class="card-header"><div><h3>Current medication</h3><p>Active treatment plan</p></div><button class="primary-button" data-action="add-med">${icon('plus',14)} Add medication</button></div><div class="document-list"><div class="document-row"><div class="snapshot-icon">${icon('pulse',14)}</div><div><strong>Cabergoline</strong><span>1 mg / week · Started 24 Feb 2026 · Ongoing</span></div><span class="status active">Active</span><button class="icon-button">${icon('more',15)}</button></div></div><div class="card-header" style="border-top:1px solid var(--line);margin-top:0"><div><h3>Adherence & side effects</h3><p>Patient reported at latest visit</p></div></div><div class="task-list"><div class="task-row"><input type="checkbox" checked><div><strong>Good adherence</strong><span>Misses less than 1 dose per month</span></div></div><div class="task-row"><input type="checkbox"><div><strong>Nausea</strong><span>No side effects reported</span></div></div></div></section><section class="card module-card"><div class="card-header"><div><h3>Dose history</h3><p>Changes and clinical rationale</p></div></div><div class="dose-history"><div class="dose-step"><strong>0.5 mg</strong><span>Jan 2025 – Feb 2026</span></div><div class="dose-arrow">→</div><div class="dose-step current"><strong>1 mg</strong><span>Feb 2026 – current</span></div><div class="dose-arrow">→</div><div class="dose-step" style="opacity:.6"><strong>Next review</strong><span>Before Sep visit</span></div></div><p class="module-note">Reason for latest change: prolactin remained elevated at 72 ng/mL on 03 Apr 2026.</p></section></div>`; }
function renderFollowup() { return `<section class="card form-card" style="max-width:none"><div class="form-section"><h3>Next appointment</h3><div class="form-grid"><div class="form-field"><label>Appointment date</label><input class="input" type="date" value="2026-09-03"></div><div class="form-field"><label>Time</label><input class="input" type="time" value="09:00"></div><div class="form-field wide"><label>Visit note</label><textarea class="textarea" placeholder="What should be reviewed at this visit?">Review prolactin trend and medication tolerance.</textarea></div></div></div><div class="form-section"><h3>Required investigations</h3><div class="task-list" style="padding:0"><label class="task-row"><input type="checkbox" checked><div><strong>MRI</strong><span>Repeat imaging if clinically indicated</span></div></label><label class="task-row"><input type="checkbox" checked><div><strong>Hormone tests</strong><span>Prolactin before appointment</span></div></label><label class="task-row"><input type="checkbox"><div><strong>Visual field</strong><span>Only if visual symptoms develop</span></div></label></div></div><div class="form-actions"><button class="secondary-button" data-action="save">Save as draft</button><button class="primary-button" data-action="schedule-followup">Schedule follow-up ${icon('calendar',14)}</button></div></section>`; }
function renderDocuments() { return `<section class="card module-card"><div class="card-header"><div><h3>Documents</h3><p>Reports and files attached to Emma’s care story</p></div><button class="primary-button" data-action="upload">${icon('upload',14)} Upload file</button></div><div class="document-list"><div class="document-row"><div class="file-icon">PDF</div><div><strong>MRI_report_12May2026.pdf</strong><span>MRI report · 1.2 MB · Uploaded 12 May 2026</span></div><button class="icon-button">${icon('download',14)}</button><button class="icon-button">${icon('more',14)}</button></div><div class="document-row"><div class="file-icon">PDF</div><div><strong>prolactin_results_Aug2026.pdf</strong><span>Laboratory report · 420 KB · Uploaded 01 Aug 2026</span></div><button class="icon-button">${icon('download',14)}</button><button class="icon-button">${icon('more',14)}</button></div><div class="document-row"><div class="file-icon" style="background:var(--purple-soft);color:var(--purple)">IMG</div><div><strong>visual_field_May2026.png</strong><span>Visual field image · 2.1 MB · Uploaded 12 May 2026</span></div><button class="icon-button">${icon('download',14)}</button><button class="icon-button">${icon('more',14)}</button></div></div></section>`; }
function detailContent() { const map = { Overview: renderOverview, Timeline: renderTimeline, Clinical: renderClinical, Hormones: renderHormones, MRI: renderMRI, Ophthalmology: () => `<section class="card"><div class="card-header"><div><h3>Ophthalmology</h3><p>Visual field assessments and ophthalmology notes</p></div><button class="primary-button" data-action="add-result">${icon('plus',14)} Add assessment</button></div><div class="empty-state">${icon('eye',28)}<p>Visual field assessment is normal.<br><small>Last reviewed 12 May 2026 by Northstar Eye Centre.</small></p></div></section>`, Treatment: renderTreatment, 'Follow-up': renderFollowup, Documents: renderDocuments }; return map[state.detailTab](); }
function renderDetail() { return shell(`<div class="patient-detail">${detailAside()}<section class="patient-main"><div class="patient-heading"><div><div class="eyebrow">Patient record</div><h1>Emma Richardson</h1><div class="subtle">PT-240184 · Last updated 2 hours ago</div></div><div class="heading-actions"><button class="secondary-button" data-action="print">${icon('download',14)} Export</button><button class="primary-button" data-action="add-event">${icon('plus',14)} Add event</button></div></div><div class="tab-nav">${detailTabs.map(tab => `<button class="tab-button ${state.detailTab === tab ? 'active' : ''}" data-tab="${tab}">${tab}</button>`).join('')}</div><div id="detail-content">${detailContent()}</div></section></div>`, 'patients'); }

function notificationPanel() { return `<div class="notification-panel"><div class="notification-head"><h3>Notifications <span class="tag review">4 new</span></h3><button class="icon-button" data-action="notifications">×</button></div><div class="notification-item unread"><div class="notification-icon red">${icon('alert',14)}</div><div><p><strong>Clinical alert:</strong> Emma Richardson reported visual deterioration.</p><span>10 minutes ago · Requires review</span></div></div><div class="notification-item unread"><div class="notification-icon gold">${icon('calendar',14)}</div><div><p><strong>Follow-up due:</strong> 8 patients are due this week.</p><span>1 hour ago · Care coordination</span></div></div><div class="notification-item"><div class="notification-icon green">${icon('check',14)}</div><div><p>MRI report uploaded for Noah Williams.</p><span>Yesterday · Documents</span></div></div><div class="notification-item"><div class="notification-icon gold">${icon('clock',14)}</div><div><p>Investigation reminder: Sophia Martinez.</p><span>Yesterday · Hormone panel</span></div></div></div>`; }

function render() { if (state.screen === 'login') return renderLogin(); if (state.screen === 'dashboard') return renderDashboard(); if (state.screen === 'patients') return renderPatients(); if (state.screen === 'create') return renderCreate(); if (state.screen === 'detail') return renderDetail(); if (state.screen === 'notifications') { state.notifications = false; return shell(`<div class="page-heading"><div><div class="eyebrow">Stay informed</div><h1>Notifications</h1><p>Review alerts, reminders and investigation updates.</p></div><button class="secondary-button" data-action="mark-read">${icon('check',14)} Mark all as read</button></div><section class="card notification-page-list"><div class="notification-item unread"><div class="notification-icon red">${icon('alert',14)}</div><div><p><strong>Clinical alert:</strong> Emma Richardson reported visual deterioration.</p><span>10 minutes ago · Requires review</span></div><button class="secondary-button" data-nav="detail">Review patient</button></div><div class="notification-item unread"><div class="notification-icon gold">${icon('calendar',14)}</div><div><p><strong>Follow-up due:</strong> 8 patients are due this week.</p><span>1 hour ago · Care coordination</span></div><button class="secondary-button" data-nav="schedule">View schedule</button></div><div class="notification-item"><div class="notification-icon green">${icon('check',14)}</div><div><p>MRI report uploaded for Noah Williams.</p><span>Yesterday · Documents</span></div></div><div class="notification-item"><div class="notification-icon gold">${icon('clock',14)}</div><div><p>Investigation reminder: Sophia Martinez.</p><span>Yesterday · Hormone panel</span></div></div></section>`, 'notifications'); } if (state.screen === 'schedule') return shell(`<div class="page-heading"><div><div class="eyebrow">Care coordination</div><h1>Schedule</h1><p>Appointments and follow-up tasks for your clinic.</p></div><button class="primary-button" data-action="schedule-followup">${icon('plus',14)} Add appointment</button></div><div class="card"><div class="card-header"><div><h3>Wednesday, 14 August 2026</h3><p>4 appointments scheduled</p></div><div class="date-chip">${icon('calendar',14)} Week view</div></div><div class="schedule-list">${[['09:00','Emma Richardson','Follow-up','ER'],['10:30','Oliver James','New patient','OJ'],['11:15','Noah Williams','Follow-up','NW'],['14:00','Sophia Martinez','Follow-up','SM'],['15:30','Liam Thompson','Review','LT']].map(x => `<div class="schedule-row"><div class="schedule-time">${x[0]}</div><div class="schedule-person"><div class="mini-avatar">${x[3]}</div><div><strong>${x[1]}</strong><span>${x[2]} · Endocrinology</span></div></div><button class="secondary-button" data-nav="detail">Open record ${icon('arrow',12)}</button></div>`).join('')}</div></div>`, 'schedule'); return renderDashboard(); }

function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => toast.classList.remove('show'), 2600); }
function rerender() {
  const output = render();
  if (typeof output === 'string') app.innerHTML = output;
}

document.addEventListener('click', (event) => {
  const nav = event.target.closest('[data-nav]');
  const tab = event.target.closest('[data-tab]');
  const filter = event.target.closest('[data-filter]');
  const action = event.target.closest('[data-action]');
  if (nav) { const destination = nav.dataset.nav; state.screen = destination === 'detail' ? 'detail' : destination; state.notifications = false; rerender(); return; }
  if (tab) { state.screen = 'detail'; state.detailTab = tab.dataset.tab; state.notifications = false; rerender(); return; }
  if (filter) { state.timelineFilter = filter.dataset.filter; rerender(); return; }
  if (action) {
    const name = action.dataset.action;
    if (name === 'login') { state.screen = 'dashboard'; rerender(); showToast('Welcome back, Dr. Chen'); }
    else if (name === 'new-patient') { state.screen = 'create'; rerender(); }
    else if (name === 'notifications') { state.notifications = !state.notifications; rerender(); }
    else if (name === 'password') { const input = document.querySelector('#password'); if (input) input.type = input.type === 'password' ? 'text' : 'password'; }
    else if (name === 'forgot') showToast('Password reset instructions are on their way.');
    else if (name === 'logout') { state.screen = 'login'; state.notifications = false; rerender(); }
    else if (name === 'schedule-followup') showToast('Follow-up scheduled and tasks created.');
    else if (name === 'save') showToast('Changes saved to the patient record.');
    else if (name === 'message') showToast('Reminder queued for Emma Richardson.');
    else if (name === 'add-event') showToast('New event form opened.');
    else if (name === 'import') showToast('Import dialog ready.');
    else if (name === 'export' || name === 'print') showToast('Export prepared for download.');
    else if (['add-result','add-mri','add-med','upload','open-file','settings','mark-read'].includes(name)) showToast(name === 'mark-read' ? 'All notifications marked as read.' : 'This action is ready for your next entry.');
  }
});
document.addEventListener('input', (event) => { if (event.target.id === 'patient-search') { state.query = event.target.value; const table = document.querySelector('#patient-table'); if (table) table.innerHTML = patientRows(); } });
document.addEventListener('submit', (event) => { if (event.target.id === 'login-form') { event.preventDefault(); state.screen = 'dashboard'; rerender(); showToast('Welcome back, Dr. Chen'); } if (event.target.id === 'patient-form') { event.preventDefault(); state.screen = 'patients'; rerender(); showToast('Patient record created successfully.'); } });

renderLogin();
